site_name: Abismal_torch
docs_dir: docs
nav:
  - Home: index.md
  - API: api.md
theme: readthedocs

plugins:
  - search
  - autorefs
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [abismal_torch]
          options:
            docstring_style: google
            annotations_path: full
            docstring_section_style: spacy
            enable_markdown: true
