trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "abismal_torch"
      name: "my_test_run"
      save_dir: null # will be set as the mtz output directory supplied by user'
  callbacks:
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: "val_loss"
        min_delta: 0.5
        patience: 2
    # - class_path: abismal_torch.callbacks.plotF.PosteriorPlotter
    #   init_args:
    #     save_every_n_epoch: 2


data:
  persistent_workers: true

seed_everything: 42
mtz_output:
  save_every_n_epoch: 2