trainer:
  default_root_dir: /Users/mai12345/Desktop/abismal_torch/tmp_outdir
  # logger:
  #   class_path: lightning.pytorch.loggers.WandbLogger
  #   init_args:
  #     project: "abismal_torch"
  #     name: "my_test_run"
  #     save_dir: null # will be set as the mtz output directory supplied by user'
  # callbacks:
  #   - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
  #     init_args:
  #       monitor: "val_loss"
  #       min_delta: 0.5
  #       patience: 2
    # - class_path: abismal_torch.callbacks.plotF.PosteriorPlotter
    #   init_args:
    #     save_every_n_epoch: 2

# Single MTZ file
data:
  rasu_configs:
    - rasu_id: 0
      dmin: 1.5
      input_files: /Users/mai12345/Desktop/unmerged.mtz

# # Single ASU Dials file
# data:
#   rasu_configs:
#     - rasu_id: 0
#       dmin: 2.0
#       input_files: 
#         - tests/data/dials.expt
#         - tests/data/dials.refl
#       cell: [10, 20, 30, 90.0, 90.0, 90.0]
#       spacegroup: "P212121"
#       anomalous: true

# # Multiple ASUs + Different file types across ASUs
# data:
#   rasu_configs:
#     - rasu_id: 0
#       dmin: 1.5
#       input_files: /Users/mai12345/Desktop/unmerged.mtz
#     - rasu_id: 1
#       dmin: 2.0
#       input_files: 
#         - tests/data/dials.refl
#         - tests/data/dials.expt
#   handler_kwargs:
#     intensity_key: "IPR"
#     sigma_key: "SIGIPR"

seed_everything: 42
mtz_output:
  save_every_n_epoch: 2