model:
  kl_weight: 1.0
  mc_samples: 32
  reindexing_ops: null

  prior_config:
    class_path: abismal_torch.prior.structure_factor.wilson.WilsonPrior
    kwargs:
      normalization_sigma: 1.0

  surrogate_posterior_config:
    class_path: abismal_torch.surrogate_posterior.structure_factor.folded_normal.FoldedNormalPosterior
    kwargs:
      init_scale: 0.1
      epsilon: 1e-12

  likelihood:
    class_path: abismal_torch.likelihood.NormalLikelihood
    # To use student t distribution, comment out the above and uncomment the below
    # class_path: abismal_torch.likelihood.student_t.StudentTLikelihood
    # init_args:
      # dof: 16

  scaling_model:
    class_path: abismal_torch.scaling.scaling.ImageScaler
    init_args:
      mlp_width: 32
      mlp_depth: 20
      use_glu: false
      activation: null # type: str, default: "SwiGLU" if use_glu is true, otherwise "ReLU"
      share_weights: false
      epsilon: 1e-12 # for numerical stability
      scaling_kl_weight: 1
      scaling_posterior: Normal
      scaling_prior: Laplace
      scaling_prior_params: [0.0, 1.0] # parameters for the scaling prior distribution
