name: Publish to TestPyPI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '1.8.3'

    - name: Install dependencies
      run: |
        poetry install

    - name: Configure TestPyPI
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}

    - name: Publish to TestPyPI
      run: |
        poetry publish --build -r testpypi
