name: Publish to TestPyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '1.8.3'

    - name: Install dependencies
      run: |
        poetry install

    - name: Configure PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }}

    - name: Publish to PyPI
      run: |
        poetry publish --build
